services:
  - type: web
    name: send-mail-web
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    plan: free
    envVars:
      - key: ACCESS_TOKEN
        value:
